name: stadium
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  dio: ^5.5.0+1
  flutter_mobx: ^2.2.1+1
  mobx: ^2.0.1
  intl: ^0.18.0
  one_context: ^4.0.0
  json_annotation: ^4.3.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.8.0
  mobx_codegen: ^2.0.1+3
  build_runner: ^2.0.3
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/maracana.jpg
    - assets/images/logo.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.otf
        - asset: assets/fonts/Poppins-Bold.otf
        - asset: assets/fonts/Poppins-ExtraBold.otf
        - asset: assets/fonts/Poppins-ExtraLight.otf
        - asset: assets/fonts/Poppins-Italic.otf
        - asset: assets/fonts/Poppins-Light.otf
        - asset: assets/fonts/Poppins-Medium.otf
        - asset: assets/fonts/Poppins-Regular.otf
        - asset: assets/fonts/Poppins-SemiBold.otf
        - asset: assets/fonts/Poppins-Thin.otf
